# Generated by Django 5.1.3 on 2024-11-26 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0002_alter_employee_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee_register_employee',
        ),
    ]
