# Generated by Django 5.1.3 on 2024-12-02 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0003_alter_employee_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table=None,
        ),
    ]
